server:
  port: 8080
spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5555/tshop?currentSchema=public
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/tiez-shop
#  redis:
#    host: localhost
#    port: 6379
#    password: # (tùy chọn, nếu Redis yêu cầu mật khẩu)
#    database: 0
#    cache:
#      type: redis
#      redis:
#        time-to-live: 600000 # Thời gian sống của cache (ms, ví dụ: 10 phút)
#        cache-null-values: false # Không lưu giá trị null vào cache
#  elasticsearch:
#    uris: http://localhost:9200
#    username: elastic
#    password: 780TnZdfArPwgiX0OsZS
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
keycloak:
  client-id: tienngv
  client-secret: bBnCGpKNDa2rhgBz81NZi3KFedJ1ftLu
  realm: tiez-shop
  base-url: http://localhost:8180
  registration-url: "${keycloak.base-url}/admin/realms/${keycloak.realm}/users"
  token-url: "${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/token"
  assign-role-url: "${keycloak.base-url}/admin/realms/${keycloak.realm}/users/{userId}/role-mappings/realm"
  role-url: "${keycloak.base-url}/admin/realms/${keycloak.realm}/roles"
